'use strict';
/* =====================================================================
   Kiko Housee — API (Vercel serverless, Express)
   Database : Postgres (Supabase)   File : Supabase Storage (bucket privat)
   Semua state ada di database — tidak ada memori/disk lokal.
   ===================================================================== */
const express = require('express');
const { Pool, types } = require('pg');
const { createClient } = require('@supabase/supabase-js');
const crypto = require('crypto');
const path = require('path');

types.setTypeParser(20, v => Number(v)); // BIGINT -> number

const MIN_WAIT = 10;
const MAX_MB = Number(process.env.MAX_UPLOAD_MB) || 50;
const BUCKET = process.env.STORAGE_BUCKET || 'files';
const PROD = process.env.NODE_ENV === 'production';
const DISCORD_OK = !!(process.env.DISCORD_CLIENT_ID && process.env.DISCORD_CLIENT_SECRET);
const GOOGLE_OK = !!(process.env.GOOGLE_CLIENT_ID && process.env.GOOGLE_CLIENT_SECRET);

const cfgErr = name => { const e = new Error(`Konfigurasi belum lengkap: isi environment variable ${name}`); e.status = 500; return e; };

/* ------------------------------ database ------------------------------ */
let pool;
function P() {
  if (!pool) {
    const url = process.env.DATABASE_URL; if (!url) throw cfgErr('DATABASE_URL');
    pool = new Pool({ connectionString: url, ssl: /localhost|127\.0\.0\.1/.test(url) ? false : { rejectUnauthorized: false }, max: 1, idleTimeoutMillis: 10000 });
  }
  return pool;
}
const q = async (sql, params = []) => (await P().query(sql, params)).rows;
const q1 = async (sql, params) => (await q(sql, params))[0] || null;
async function tx(fn) {
  const c = await P().connect();
  try {
    await c.query('BEGIN');
    const r = await fn((s, p = []) => c.query(s, p).then(x => x.rows));
    await c.query('COMMIT');
    return r;
  } catch (e) { try { await c.query('ROLLBACK'); } catch (_) {} throw e; }
  finally { c.release(); }
}

const SCHEMA = `
CREATE TABLE IF NOT EXISTS users(id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, username TEXT NOT NULL, pass TEXT NOT NULL, role TEXT NOT NULL, created BIGINT NOT NULL);
CREATE UNIQUE INDEX IF NOT EXISTS users_username_ci ON users(lower(username));
CREATE TABLE IF NOT EXISTS sessions(token TEXT PRIMARY KEY, user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE, expires BIGINT NOT NULL);
CREATE TABLE IF NOT EXISTS links(id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, title TEXT NOT NULL, descr TEXT DEFAULT '', type TEXT NOT NULL, access TEXT NOT NULL DEFAULT 'all', url TEXT, file_name TEXT, file_key TEXT, size INTEGER DEFAULT 0, downloads INTEGER DEFAULT 0, created BIGINT NOT NULL);
CREATE TABLE IF NOT EXISTS reqs(id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, link_id INTEGER NOT NULL REFERENCES links(id) ON DELETE CASCADE, platform TEXT NOT NULL, label TEXT DEFAULT '', url TEXT NOT NULL, target_id TEXT DEFAULT '', sort INTEGER DEFAULT 0);
CREATE TABLE IF NOT EXISTS verifs(viewer TEXT NOT NULL, req_id INTEGER NOT NULL REFERENCES reqs(id) ON DELETE CASCADE, method TEXT NOT NULL, ts BIGINT NOT NULL, PRIMARY KEY(viewer, req_id));
CREATE TABLE IF NOT EXISTS starts(viewer TEXT NOT NULL, req_id INTEGER NOT NULL REFERENCES reqs(id) ON DELETE CASCADE, ts BIGINT NOT NULL, PRIMARY KEY(viewer, req_id));
CREATE TABLE IF NOT EXISTS announcements(id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, title TEXT NOT NULL, body TEXT NOT NULL, link_id INTEGER REFERENCES links(id) ON DELETE SET NULL, created BIGINT NOT NULL);
CREATE TABLE IF NOT EXISTS settings(k TEXT PRIMARY KEY, v TEXT);
CREATE TABLE IF NOT EXISTS login_fail(ip TEXT NOT NULL, ts BIGINT NOT NULL);
CREATE INDEX IF NOT EXISTS login_fail_ip ON login_fail(ip, ts);
`;

/* ------------------------------ helpers ------------------------------ */
const sha = s => crypto.createHash('sha256').update(s).digest('hex');
const rand = (n = 24) => crypto.randomBytes(n).toString('hex');
function hashPw(pw) {
  const salt = crypto.randomBytes(16);
  return salt.toString('hex') + ':' + crypto.scryptSync(pw, salt, 64).toString('hex');
}
function checkPw(pw, stored) {
  try {
    const [s, h] = stored.split(':');
    return crypto.timingSafeEqual(crypto.scryptSync(pw, Buffer.from(s, 'hex'), 64), Buffer.from(h, 'hex'));
  } catch (e) { return false; }
}
function parseCookies(req) {
  const o = {};
  (req.headers.cookie || '').split(';').forEach(p => {
    const i = p.indexOf('=');
    if (i > 0) { try { o[p.slice(0, i).trim()] = decodeURIComponent(p.slice(i + 1).trim()); } catch (e) {} }
  });
  return o;
}
function setCookie(res, name, val, maxAge) {
  res.append('Set-Cookie', `${name}=${encodeURIComponent(val)}; Path=/; HttpOnly; SameSite=Lax; Max-Age=${maxAge}${PROD ? '; Secure' : ''}`);
}
const okUrl = u => { try { const x = new URL(u); return x.protocol === 'https:' || x.protocol === 'http:'; } catch (e) { return false; } };
const clean = (s, max) => String(s == null ? '' : s).replace(/[\u0000-\u0008\u000B\u000C\u000E-\u001F]/g, '').trim().slice(0, max);
const safeName = n => clean(n, 200).replace(/[\\/:*?"<>|]/g, '_') || 'file';
const num = v => (Number.isInteger(Number(v)) && Number(v) > 0 && Number(v) < 2147483647) ? Number(v) : 0;
const PLATFORMS = ['youtube', 'instagram', 'tiktok', 'twitter', 'facebook', 'twitch', 'github', 'discord', 'telegram', 'other'];
const baseUrl = req => (process.env.BASE_URL || `${req.headers['x-forwarded-proto'] || 'https'}://${req.headers.host}`).replace(/\/+$/, '');

const DEFAULTS = {
  siteName: 'Kiko Housee',
  tagline: 'Arsip file pilihan. Gratis, tinggal follow dulu.',
  about: 'Tempat Kiko menyimpan file, tools, dan bahan yang dibagikan ke komunitas. Selesaikan langkah singkat di tiap file, lalu unduh.',
  discord: 'https://discord.gg/U6sFp89fFa'
};
async function getSettings() {
  const s = { ...DEFAULTS };
  for (const r of await q('SELECT k,v FROM settings')) s[r.k] = r.v;
  return s;
}

/* signed OAuth state (stateless -> aman untuk serverless) */
function signState(o) {
  if (!process.env.SESSION_SECRET) throw cfgErr('SESSION_SECRET');
  const p = Buffer.from(JSON.stringify(o)).toString('base64url');
  return p + '.' + crypto.createHmac('sha256', process.env.SESSION_SECRET).update(p).digest('base64url');
}
function readState(t, kind, viewer) {
  try {
    const [p, s] = String(t).split('.');
    const e = crypto.createHmac('sha256', process.env.SESSION_SECRET).update(p).digest('base64url');
    if (s.length !== e.length || !crypto.timingSafeEqual(Buffer.from(s), Buffer.from(e))) return null;
    const o = JSON.parse(Buffer.from(p, 'base64url').toString());
    return (o.exp > Date.now() && o.kind === kind && o.viewer === viewer) ? o : null;
  } catch (e) { return null; }
}

/* Supabase Storage */
let sb, bucketReady;
async function storage() {
  if (!process.env.SUPABASE_URL) throw cfgErr('SUPABASE_URL');
  if (!process.env.SUPABASE_SERVICE_ROLE_KEY) throw cfgErr('SUPABASE_SERVICE_ROLE_KEY');
  if (!sb) sb = createClient(process.env.SUPABASE_URL, process.env.SUPABASE_SERVICE_ROLE_KEY, { auth: { persistSession: false } });
  if (!bucketReady) { await sb.storage.createBucket(BUCKET, { public: false }).catch(() => {}); bucketReady = true; }
  return sb.storage.from(BUCKET);
}

/* init: buat tabel + seed Owner (sekali per instance) */
let ready;
function init() {
  if (!ready) ready = (async () => {
    try { await q(SCHEMA); } catch (e) { console.error('schema:', e.message); }
    if (!(await q1("SELECT 1 x FROM users WHERE role='owner'"))) {
      const u = process.env.OWNER_USER, p = process.env.OWNER_PASS;
      if (!u || !p) throw cfgErr('OWNER_USER dan OWNER_PASS');
      await q("INSERT INTO users(username,pass,role,created) SELECT $1::text,$2::text,'owner',$3::bigint WHERE NOT EXISTS (SELECT 1 FROM users WHERE role='owner') ON CONFLICT DO NOTHING", [clean(u, 24), hashPw(p), Date.now()]);
    }
  })().catch(e => { ready = null; throw e; });
  return ready;
}

/* ------------------------------ app ------------------------------ */
const app = express();
app.set('trust proxy', 1);
app.disable('x-powered-by');
app.use(express.json({ limit: '200kb' }));
const H = fn => (req, res, next) => Promise.resolve(fn(req, res, next)).catch(next);

app.use(H(async (req, res, next) => {
  await init();
  const c = parseCookies(req);
  let user = null;
  if (c.kh_s) user = await q1('SELECT u.id,u.username,u.role FROM sessions s JOIN users u ON u.id=s.user_id WHERE s.token=$1 AND s.expires>$2', [sha(c.kh_s), Date.now()]);
  let g = c.kh_g;
  if (!g || !/^[a-f0-9]{32}$/.test(g)) { g = rand(16); setCookie(res, 'kh_g', g, 31536000); }
  req.user = user;
  req.viewer = user ? 'u:' + user.id : 'g:' + g;
  next();
}));
app.use('/api', (req, res, next) => {
  if (!['GET', 'HEAD', 'OPTIONS'].includes(req.method) && req.headers['x-kh'] !== '1') return res.status(403).json({ error: 'Permintaan ditolak' });
  next();
});
const needOwner = (req, res, next) => (req.user && req.user.role === 'owner') ? next() : res.status(403).json({ error: 'Khusus Owner' });

/* ------------------------------ auth ------------------------------ */
app.get('/api/bootstrap', H(async (req, res) => {
  res.json({
    me: req.user ? { username: req.user.username, role: req.user.role } : null,
    settings: await getSettings(), oauth: { discord: DISCORD_OK, google: GOOGLE_OK }, minWait: MIN_WAIT, maxMb: MAX_MB
  });
}));
app.post('/api/login', H(async (req, res) => {
  const now = Date.now();
  const f = await q1('SELECT COUNT(*)::int c FROM login_fail WHERE ip=$1 AND ts>$2', [req.ip, now - 600000]);
  if (f.c >= 8) return res.status(429).json({ error: 'Terlalu banyak percobaan. Coba lagi 10 menit.' });
  const u = await q1('SELECT * FROM users WHERE lower(username)=lower($1)', [clean(req.body.username, 40)]);
  if (!u || !checkPw(String(req.body.password || ''), u.pass)) {
    await q('INSERT INTO login_fail(ip,ts) VALUES($1,$2)', [req.ip, now]);
    await q('DELETE FROM login_fail WHERE ts<$1', [now - 3600000]);
    return res.status(401).json({ error: 'Username atau password salah' });
  }
  await q('DELETE FROM login_fail WHERE ip=$1', [req.ip]);
  const t = rand(32);
  await q('INSERT INTO sessions(token,user_id,expires) VALUES($1,$2,$3)', [sha(t), u.id, now + 30 * 86400000]);
  await q('DELETE FROM sessions WHERE expires<$1', [now]);
  setCookie(res, 'kh_s', t, 30 * 86400);
  res.json({ me: { username: u.username, role: u.role } });
}));
app.post('/api/logout', H(async (req, res) => {
  const c = parseCookies(req);
  if (c.kh_s) await q('DELETE FROM sessions WHERE token=$1', [sha(c.kh_s)]);
  setCookie(res, 'kh_s', '', 0);
  res.json({ ok: 1 });
}));

/* ------------------------------ public: links ------------------------------ */
const canSee = (req, l) => l.access === 'all' || !!req.user;
const pub = l => ({ id: l.id, title: l.title, desc: l.descr, type: l.type, access: l.access, size: l.size, fileName: l.file_name, downloads: l.downloads, created: l.created });
const progressOf = (req, linkId) => q1(
  `SELECT (SELECT COUNT(*) FROM reqs WHERE link_id=$1)::int total,
          (SELECT COUNT(*) FROM reqs r JOIN verifs v ON v.req_id=r.id AND v.viewer=$2 WHERE r.link_id=$1)::int done`, [linkId, req.viewer]);
function modeOf(r) {
  if (r.platform === 'discord' && r.target_id && DISCORD_OK) return 'discord';
  if (r.platform === 'youtube' && r.target_id && GOOGLE_OK) return 'youtube';
  return 'timer';
}

app.get('/api/links', H(async (req, res) => {
  const rows = await q(`SELECT l.*,
    (SELECT COUNT(*) FROM reqs WHERE link_id=l.id)::int total,
    (SELECT COUNT(*) FROM reqs r JOIN verifs v ON v.req_id=r.id AND v.viewer=$1 WHERE r.link_id=l.id)::int done
    FROM links l ORDER BY l.created DESC`, [req.viewer]);
  res.json({
    links: rows.filter(l => canSee(req, l)).map(l => ({ ...pub(l), progress: { done: l.done, total: l.total } })),
    hidden: rows.filter(l => !canSee(req, l)).length
  });
}));
app.get('/api/links/:id', H(async (req, res) => {
  const l = await q1('SELECT * FROM links WHERE id=$1', [num(req.params.id)]);
  if (!l) return res.status(404).json({ error: 'Tidak ditemukan' });
  if (!canSee(req, l)) return res.status(403).json({ error: 'Khusus member' });
  const done = new Set((await q('SELECT req_id FROM verifs WHERE viewer=$1', [req.viewer])).map(x => x.req_id));
  const reqs = (await q('SELECT * FROM reqs WHERE link_id=$1 ORDER BY sort,id', [l.id]))
    .map(r => ({ id: r.id, platform: r.platform, label: r.label, url: r.url, mode: modeOf(r), done: done.has(r.id) }));
  res.json({ ...pub(l), reqs });
}));

async function getReq(req, linkId, reqId) {
  const l = await q1('SELECT * FROM links WHERE id=$1', [num(linkId)]);
  if (!l || !canSee(req, l)) return {};
  return { l, r: await q1('SELECT * FROM reqs WHERE id=$1 AND link_id=$2', [num(reqId), l.id]) };
}
app.post('/api/links/:id/reqs/:rid/start', H(async (req, res) => {
  const { r } = await getReq(req, req.params.id, req.params.rid);
  if (!r) return res.status(404).json({ error: 'Tidak ditemukan' });
  if (modeOf(r) !== 'timer') return res.status(400).json({ error: 'Gunakan verifikasi otomatis' });
  await q('INSERT INTO starts(viewer,req_id,ts) VALUES($1,$2,$3) ON CONFLICT (viewer,req_id) DO UPDATE SET ts=EXCLUDED.ts', [req.viewer, r.id, Date.now()]);
  res.json({ ok: 1 });
}));
app.post('/api/links/:id/reqs/:rid/verify', H(async (req, res) => {
  const { r } = await getReq(req, req.params.id, req.params.rid);
  if (!r) return res.status(404).json({ error: 'Tidak ditemukan' });
  if (modeOf(r) !== 'timer') return res.status(400).json({ error: 'Gunakan verifikasi otomatis' });
  const s = await q1('SELECT ts FROM starts WHERE viewer=$1 AND req_id=$2', [req.viewer, r.id]);
  if (!s) return res.status(400).json({ error: 'Buka halaman tugasnya dulu' });
  if (Date.now() - s.ts < MIN_WAIT * 1000) return res.status(400).json({ error: 'Tunggu beberapa detik lagi' });
  if (req.body.left !== true) return res.status(400).json({ error: 'Buka tab tugas, lalu kembali ke sini' });
  await q('DELETE FROM starts WHERE viewer=$1 AND req_id=$2', [req.viewer, r.id]);
  await markVerified(req.viewer, r.id, 'timer');
  res.json({ ok: 1 });
}));
const markVerified = (viewer, reqId, method) =>
  q('INSERT INTO verifs(viewer,req_id,method,ts) VALUES($1,$2,$3,$4) ON CONFLICT (viewer,req_id) DO UPDATE SET method=EXCLUDED.method, ts=EXCLUDED.ts', [viewer, reqId, method, Date.now()]);

/* ------------------------------ OAuth: Discord & Google ------------------------------ */
const back = (res, linkId, status) => res.redirect(`/#/file/${linkId}?v=${status}`);
async function postForm(url, data) {
  const r = await fetch(url, { method: 'POST', headers: { 'content-type': 'application/x-www-form-urlencoded' }, body: new URLSearchParams(data) });
  return r.json();
}
const mkState = (req, kind, r) => signState({ kind, viewer: req.viewer, linkId: r.link_id, reqId: r.id, exp: Date.now() + 600000 });

app.get('/auth/discord', H(async (req, res) => {
  const { r } = await getReq(req, req.query.link, req.query.req);
  if (!DISCORD_OK || !r || modeOf(r) !== 'discord') return res.status(400).send('Tidak tersedia');
  res.redirect('https://discord.com/oauth2/authorize?' + new URLSearchParams({
    client_id: process.env.DISCORD_CLIENT_ID, response_type: 'code', scope: 'identify guilds',
    redirect_uri: baseUrl(req) + '/auth/discord/callback', state: mkState(req, 'discord', r)
  }));
}));
app.get('/auth/discord/callback', H(async (req, res) => {
  const st = readState(req.query.state, 'discord', req.viewer);
  if (!st) return res.status(400).send('Sesi verifikasi tidak valid atau kedaluwarsa. Ulangi dari halaman file.');
  if (!req.query.code) return back(res, st.linkId, 'fail');
  try {
    const tok = await postForm('https://discord.com/api/oauth2/token', {
      client_id: process.env.DISCORD_CLIENT_ID, client_secret: process.env.DISCORD_CLIENT_SECRET,
      grant_type: 'authorization_code', code: String(req.query.code), redirect_uri: baseUrl(req) + '/auth/discord/callback'
    });
    if (!tok.access_token) return back(res, st.linkId, 'err');
    const guilds = await (await fetch('https://discord.com/api/users/@me/guilds', { headers: { authorization: 'Bearer ' + tok.access_token } })).json();
    const r = await q1('SELECT * FROM reqs WHERE id=$1', [st.reqId]);
    if (!Array.isArray(guilds) || !r) return back(res, st.linkId, 'err');
    if (guilds.some(g => g.id === r.target_id)) { await markVerified(st.viewer, r.id, 'discord'); return back(res, st.linkId, 'ok'); }
    back(res, st.linkId, 'fail');
  } catch (e) { back(res, st.linkId, 'err'); }
}));

app.get('/auth/google', H(async (req, res) => {
  const { r } = await getReq(req, req.query.link, req.query.req);
  if (!GOOGLE_OK || !r || modeOf(r) !== 'youtube') return res.status(400).send('Tidak tersedia');
  res.redirect('https://accounts.google.com/o/oauth2/v2/auth?' + new URLSearchParams({
    client_id: process.env.GOOGLE_CLIENT_ID, response_type: 'code', scope: 'https://www.googleapis.com/auth/youtube.readonly',
    redirect_uri: baseUrl(req) + '/auth/google/callback', state: mkState(req, 'youtube', r), prompt: 'select_account'
  }));
}));
app.get('/auth/google/callback', H(async (req, res) => {
  const st = readState(req.query.state, 'youtube', req.viewer);
  if (!st) return res.status(400).send('Sesi verifikasi tidak valid atau kedaluwarsa. Ulangi dari halaman file.');
  if (!req.query.code) return back(res, st.linkId, 'fail');
  try {
    const tok = await postForm('https://oauth2.googleapis.com/token', {
      client_id: process.env.GOOGLE_CLIENT_ID, client_secret: process.env.GOOGLE_CLIENT_SECRET,
      grant_type: 'authorization_code', code: String(req.query.code), redirect_uri: baseUrl(req) + '/auth/google/callback'
    });
    if (!tok.access_token) return back(res, st.linkId, 'err');
    const r = await q1('SELECT * FROM reqs WHERE id=$1', [st.reqId]);
    if (!r) return back(res, st.linkId, 'err');
    const qs = new URLSearchParams({ part: 'id', mine: 'true', forChannelId: r.target_id, maxResults: '1' });
    const j = await (await fetch('https://www.googleapis.com/youtube/v3/subscriptions?' + qs, { headers: { authorization: 'Bearer ' + tok.access_token } })).json();
    if (j.error) return back(res, st.linkId, 'err');
    if (Array.isArray(j.items) && j.items.length) { await markVerified(st.viewer, r.id, 'youtube'); return back(res, st.linkId, 'ok'); }
    back(res, st.linkId, 'fail');
  } catch (e) { back(res, st.linkId, 'err'); }
}));

/* ------------------------------ download (dijaga di server) ------------------------------ */
app.post('/api/links/:id/download', H(async (req, res) => {
  const l = await q1('SELECT * FROM links WHERE id=$1', [num(req.params.id)]);
  if (!l) return res.status(404).json({ error: 'Tidak ditemukan' });
  if (!canSee(req, l)) return res.status(403).json({ error: 'Khusus member' });
  const p = await progressOf(req, l.id);
  if (p.done < p.total) return res.status(403).json({ error: 'Selesaikan semua tugas dulu' });
  if (l.type === 'url') {
    await q('UPDATE links SET downloads=downloads+1 WHERE id=$1', [l.id]);
    return res.json({ url: l.url, external: true });
  }
  const s = await storage();
  const { data, error } = await s.createSignedUrl(l.file_key, 60, { download: l.file_name });
  if (error || !data) return res.status(500).json({ error: 'File tidak ditemukan di penyimpanan' });
  await q('UPDATE links SET downloads=downloads+1 WHERE id=$1', [l.id]);
  res.json({ url: data.signedUrl });
}));

/* ------------------------------ announcements ------------------------------ */
app.get('/api/announcements', H(async (req, res) => {
  const rows = await q('SELECT a.*, l.title link_title, l.access link_access FROM announcements a LEFT JOIN links l ON l.id=a.link_id ORDER BY a.created DESC LIMIT 100');
  res.json({
    items: rows.map(a => ({
      id: a.id, title: a.title, body: a.body, created: a.created,
      linkId: (a.link_id && (a.link_access === 'all' || req.user)) ? a.link_id : null, linkTitle: a.link_title
    }))
  });
}));
app.post('/api/admin/announcements', needOwner, H(async (req, res) => {
  const title = clean(req.body.title, 120), body = clean(req.body.body, 2000);
  if (!title || !body) return res.status(400).json({ error: 'Judul dan isi wajib diisi' });
  await q('INSERT INTO announcements(title,body,link_id,created) VALUES($1,$2,$3,$4)', [title, body, num(req.body.linkId) || null, Date.now()]);
  res.json({ ok: 1 });
}));
app.delete('/api/admin/announcements/:id', needOwner, H(async (req, res) => {
  await q('DELETE FROM announcements WHERE id=$1', [num(req.params.id)]); res.json({ ok: 1 });
}));

/* ------------------------------ owner: links ------------------------------ */
app.get('/api/admin/links', needOwner, H(async (req, res) => {
  const rows = await q('SELECT * FROM links ORDER BY created DESC');
  const reqs = await q('SELECT id,link_id,platform,label,url,target_id FROM reqs ORDER BY sort,id');
  res.json({ links: rows.map(l => ({ ...pub(l), url: l.url, reqs: reqs.filter(r => r.link_id === l.id).map(({ link_id, ...r }) => r) })) });
}));

/* langkah 1 upload: server beri izin unggah langsung ke Supabase Storage (menghindari batas 4.5 MB Vercel) */
app.post('/api/admin/upload-url', needOwner, H(async (req, res) => {
  const size = Number(req.body.size) || 0;
  if (size <= 0) return res.status(400).json({ error: 'File kosong' });
  if (size > MAX_MB * 1024 * 1024) return res.status(413).json({ error: `File terlalu besar (maks ${MAX_MB} MB)` });
  if (!process.env.SUPABASE_ANON_KEY) throw cfgErr('SUPABASE_ANON_KEY');
  const s = await storage(); const key = rand(16);
  const { data, error } = await s.createSignedUploadUrl(key);
  if (error || !data) return res.status(500).json({ error: 'Gagal menyiapkan unggahan: ' + (error && error.message) });
  res.json({ key, token: data.token, url: process.env.SUPABASE_URL, anonKey: process.env.SUPABASE_ANON_KEY, bucket: BUCKET });
}));

function parseLinkBody(b) {
  const out = {
    title: clean(b.title, 140), descr: clean(b.desc, 600), type: b.type === 'url' ? 'url' : 'file',
    access: b.access === 'member' ? 'member' : 'all', url: clean(b.url, 1000), announce: !!b.announce, reqs: [], file: null
  };
  if (!out.title) return { error: 'Judul wajib diisi' };
  if (out.type === 'url' && !okUrl(out.url)) return { error: 'URL download tidak valid' };
  if (b.file && out.type === 'file') {
    if (!/^[a-f0-9]{32}$/.test(String(b.file.key))) return { error: 'Data file tidak valid' };
    out.file = { key: b.file.key, name: safeName(b.file.name), size: Math.max(0, Math.min(Number(b.file.size) || 0, 2e9)) };
  }
  for (const r of (Array.isArray(b.reqs) ? b.reqs : []).slice(0, 12)) {
    const item = { id: num(r.id) || null, platform: PLATFORMS.includes(r.platform) ? r.platform : 'other', label: clean(r.label, 100), url: clean(r.url, 1000), target_id: clean(r.target_id, 100) };
    if (!okUrl(item.url)) return { error: 'URL tugas harus diawali https://' };
    out.reqs.push(item);
  }
  return { d: out };
}
async function saveReqs(t, linkId, reqs) {
  const ex = new Map((await t('SELECT * FROM reqs WHERE link_id=$1', [linkId])).map(x => [x.id, x]));
  const keep = new Set(); let sort = 0;
  for (const r of reqs) {
    const old = r.id && ex.get(r.id);
    if (old) {
      await t('UPDATE reqs SET platform=$1,label=$2,url=$3,target_id=$4,sort=$5 WHERE id=$6', [r.platform, r.label, r.url, r.target_id, sort++, r.id]);
      if (old.platform !== r.platform || old.target_id !== r.target_id) await t('DELETE FROM verifs WHERE req_id=$1', [r.id]);
      keep.add(r.id);
    } else {
      const [row] = await t('INSERT INTO reqs(link_id,platform,label,url,target_id,sort) VALUES($1,$2,$3,$4,$5,$6) RETURNING id', [linkId, r.platform, r.label, r.url, r.target_id, sort++]);
      keep.add(row.id);
    }
  }
  for (const id of ex.keys()) if (!keep.has(id)) await t('DELETE FROM reqs WHERE id=$1', [id]);
}
const rmFile = async key => { if (key) { try { await (await storage()).remove([key]); } catch (e) {} } };

app.post('/api/admin/links', needOwner, H(async (req, res) => {
  const p = parseLinkBody(req.body);
  if (p.error) return res.status(400).json({ error: p.error });
  const d = p.d;
  if (d.type === 'file' && !d.file) return res.status(400).json({ error: 'Pilih file yang mau diunggah' });
  const id = await tx(async t => {
    const [row] = await t('INSERT INTO links(title,descr,type,access,url,file_name,file_key,size,created) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9) RETURNING id',
      [d.title, d.descr, d.type, d.access, d.type === 'url' ? d.url : null, d.file ? d.file.name : null, d.file ? d.file.key : null, d.file ? d.file.size : 0, Date.now()]);
    await saveReqs(t, row.id, d.reqs.map(r => ({ ...r, id: null })));
    if (d.announce) await t('INSERT INTO announcements(title,body,link_id,created) VALUES($1,$2,$3,$4)',
      ['File baru: ' + d.title, (d.descr || 'File baru sudah diunggah.') + ' Selesaikan langkah singkatnya untuk mengunduh.', row.id, Date.now()]);
    return row.id;
  });
  res.json({ id });
}));
app.put('/api/admin/links/:id', needOwner, H(async (req, res) => {
  const l = await q1('SELECT * FROM links WHERE id=$1', [num(req.params.id)]);
  if (!l) return res.status(404).json({ error: 'Tidak ditemukan' });
  const p = parseLinkBody(req.body);
  if (p.error) return res.status(400).json({ error: p.error });
  const d = p.d;
  let name = l.file_name, key = l.file_key, size = l.size, oldKey = null;
  if (d.type === 'url') { oldKey = l.file_key; name = key = null; size = 0; }
  else if (d.file) { oldKey = l.file_key; name = d.file.name; key = d.file.key; size = d.file.size; }
  else if (!key) return res.status(400).json({ error: 'Pilih file yang mau diunggah' });
  await tx(async t => {
    await t('UPDATE links SET title=$1,descr=$2,type=$3,access=$4,url=$5,file_name=$6,file_key=$7,size=$8 WHERE id=$9',
      [d.title, d.descr, d.type, d.access, d.type === 'url' ? d.url : null, name, key, size, l.id]);
    await saveReqs(t, l.id, d.reqs);
  });
  if (oldKey && oldKey !== key) await rmFile(oldKey);
  res.json({ id: l.id });
}));
app.delete('/api/admin/links/:id', needOwner, H(async (req, res) => {
  const l = await q1('SELECT * FROM links WHERE id=$1', [num(req.params.id)]);
  if (l) { await q('DELETE FROM links WHERE id=$1', [l.id]); await rmFile(l.file_key); }
  res.json({ ok: 1 });
}));

/* ------------------------------ owner: members & settings ------------------------------ */
app.get('/api/admin/members', needOwner, H(async (req, res) => {
  res.json({ members: await q("SELECT id,username,created FROM users WHERE role='member' ORDER BY created DESC") });
}));
app.post('/api/admin/members', needOwner, H(async (req, res) => {
  const u = clean(req.body.username, 24), p = String(req.body.password || '');
  if (!/^[A-Za-z0-9_.-]{3,24}$/.test(u)) return res.status(400).json({ error: 'Username 3–24 karakter (huruf, angka, _ . -)' });
  if (p.length < 6) return res.status(400).json({ error: 'Password minimal 6 karakter' });
  if (await q1('SELECT 1 x FROM users WHERE lower(username)=lower($1)', [u])) return res.status(400).json({ error: 'Username sudah dipakai' });
  await q("INSERT INTO users(username,pass,role,created) VALUES($1,$2,'member',$3)", [u, hashPw(p), Date.now()]);
  res.json({ ok: 1 });
}));
app.put('/api/admin/members/:id', needOwner, H(async (req, res) => {
  const p = String(req.body.password || '');
  if (p.length < 6) return res.status(400).json({ error: 'Password minimal 6 karakter' });
  const id = num(req.params.id);
  await q("UPDATE users SET pass=$1 WHERE id=$2 AND role='member'", [hashPw(p), id]);
  await q('DELETE FROM sessions WHERE user_id=$1', [id]);
  res.json({ ok: 1 });
}));
app.delete('/api/admin/members/:id', needOwner, H(async (req, res) => {
  await q("DELETE FROM users WHERE id=$1 AND role='member'", [num(req.params.id)]); res.json({ ok: 1 });
}));
app.put('/api/admin/settings', needOwner, H(async (req, res) => {
  const b = req.body, d = clean(b.discord, 300);
  if (!okUrl(d)) return res.status(400).json({ error: 'Link Discord tidak valid' });
  const rows = { siteName: clean(b.siteName, 40) || DEFAULTS.siteName, tagline: clean(b.tagline, 160), about: clean(b.about, 800), discord: d };
  for (const [k, v] of Object.entries(rows)) await q('INSERT INTO settings(k,v) VALUES($1,$2) ON CONFLICT (k) DO UPDATE SET v=EXCLUDED.v', [k, v]);
  res.json({ ok: 1 });
}));
app.put('/api/admin/password', needOwner, H(async (req, res) => {
  const u = await q1('SELECT * FROM users WHERE id=$1', [req.user.id]);
  if (!checkPw(String(req.body.current || ''), u.pass)) return res.status(400).json({ error: 'Password lama salah' });
  const p = String(req.body.password || '');
  if (p.length < 8) return res.status(400).json({ error: 'Password baru minimal 8 karakter' });
  await q('UPDATE users SET pass=$1 WHERE id=$2', [hashPw(p), u.id]);
  res.json({ ok: 1 });
}));

/* ------------------------------ errors & local dev ------------------------------ */
app.use((err, req, res, next) => {
  console.error(err);
  res.status(err.status || 500).json({ error: err.status ? err.message : 'Terjadi kesalahan di server' });
});

module.exports = app;

if (require.main === module) { // jalankan lokal: node api/index.js
  app.use(express.static(path.join(__dirname, '..', 'public')));
  const port = Number(process.env.PORT) || 3000;
  app.listen(port, () => console.log(`[Kiko Housee] http://localhost:${port}`));
}
